[
  {"lib/mix/tasks/worth.ex", :callback_info_missing},
  {"lib/mix/tasks/worth.export.ex", :callback_info_missing},
  {"lib/mix/tasks/worth.export.ex", :unknown_function},
  {"lib/mix/tasks/worth.import.ex", :callback_info_missing},
  {"lib/mix/tasks/worth.import.ex", :unknown_function},
  {"lib/worth/mcp/server/tools/memory_query.ex", :callback_type_mismatch},
  {"lib/worth/mcp/server/tools/memory_write.ex", :callback_type_mismatch},
  {"lib/worth/mcp/server/tools/skill_list.ex", :callback_type_mismatch},
  {"lib/worth/mcp/server/tools/skill_read.ex", :callback_type_mismatch},
  {"lib/worth/mcp/server/tools/workspace_status.ex", :callback_type_mismatch},
  {"lib/worth/log_handler.ex", :pattern_match},
  {"lib/worth/log_handler.ex", :pattern_match_cov},
  {"lib/worth/workspace/learning.ex", :pattern_match},
  {"lib/worth/skill/service.ex", :guard_fail},
  {"lib/worth/application.ex", :unknown_function},
  {"lib/worth/brain.ex", :unknown_function},
  {"lib/worth/orchestration/experiment_service.ex", :unknown_function},
  {"lib/worth/orchestration/strategies/ecosystem.ex", :callback_info_missing},
  {"lib/worth/orchestration/strategies/evolutionary.ex", :callback_info_missing},
  {"lib/worth/orchestration/strategies/holonic.ex", :callback_info_missing},
  {"lib/worth/orchestration/strategies/stigmergy.ex", :callback_info_missing},
  {"lib/worth/orchestration/strategies/swarm.ex", :callback_info_missing}
]
