%Doctor.Config{
  min_module_doc_coverage: 0,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 40,
  min_overall_spec_coverage: 0,
  min_overall_moduledoc_coverage: 100,
  struct_type_spec_required: false,
  ignore_modules: [
    # Submodules generated by `use Cldr` in lib/worth/cldr.ex.
    # We don't control their docstrings.
    Worth.Cldr.Number.System,
    Worth.Cldr.Number.Symbol,
    Worth.Cldr.Number.Formatter.Decimal,
    Worth.Cldr.Currency,
    Worth.Cldr.Rbnf.Spellout,
    Worth.Cldr.Rbnf.Ordinal,
    Worth.Cldr.Rbnf.NumberSystem,
    Worth.Cldr.Number.Transliterate,
    Worth.Cldr.Number.PluralRule.Range,
    Worth.Cldr.Number.Ordinal,
    Worth.Cldr.Number.Format,
    Worth.Cldr.Number.Cardinal,
    Worth.Cldr.Number,
    Worth.Cldr.Money,
    Worth.Cldr.Locale,
    Worth.Cldr.AcceptLanguage
  ]
}
